/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.videoplaza.avro.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4354479586924594043L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Record\",\"namespace\":\"com.videoplaza.avro.schema\",\"fields\":[{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"attributes\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.nio.ByteBuffer data;
   private java.util.Map<java.lang.String,java.lang.String> attributes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Record() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   * @param attributes The new value for attributes
   */
  public Record(java.nio.ByteBuffer data, java.util.Map<java.lang.String,java.lang.String> attributes) {
    this.data = data;
    this.attributes = attributes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    case 1: return attributes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.nio.ByteBuffer)value$; break;
    case 1: attributes = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }


  /**
   * Gets the value of the 'attributes' field.
   * @return The value of the 'attributes' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getAttributes() {
    return attributes;
  }


  /**
   * Creates a new Record RecordBuilder.
   * @return A new Record RecordBuilder
   */
  public static com.videoplaza.avro.schema.Record.Builder newBuilder() {
    return new com.videoplaza.avro.schema.Record.Builder();
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Record RecordBuilder
   */
  public static com.videoplaza.avro.schema.Record.Builder newBuilder(com.videoplaza.avro.schema.Record.Builder other) {
    return new com.videoplaza.avro.schema.Record.Builder(other);
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Record instance.
   * @param other The existing instance to copy.
   * @return A new Record RecordBuilder
   */
  public static com.videoplaza.avro.schema.Record.Builder newBuilder(com.videoplaza.avro.schema.Record other) {
    return new com.videoplaza.avro.schema.Record.Builder(other);
  }

  /**
   * RecordBuilder for Record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Record>
    implements org.apache.avro.data.RecordBuilder<Record> {

    private java.nio.ByteBuffer data;
    private java.util.Map<java.lang.String,java.lang.String> attributes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.videoplaza.avro.schema.Record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attributes)) {
        this.attributes = data().deepCopy(fields()[1].schema(), other.attributes);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Record instance
     * @param other The existing instance to copy.
     */
    private Builder(com.videoplaza.avro.schema.Record other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.attributes)) {
        this.attributes = data().deepCopy(fields()[1].schema(), other.attributes);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public com.videoplaza.avro.schema.Record.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public com.videoplaza.avro.schema.Record.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'attributes' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getAttributes() {
      return attributes;
    }

    /**
      * Sets the value of the 'attributes' field.
      * @param value The value of 'attributes'.
      * @return This builder.
      */
    public com.videoplaza.avro.schema.Record.Builder setAttributes(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[1], value);
      this.attributes = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'attributes' field has been set.
      * @return True if the 'attributes' field has been set, false otherwise.
      */
    public boolean hasAttributes() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'attributes' field.
      * @return This builder.
      */
    public com.videoplaza.avro.schema.Record.Builder clearAttributes() {
      attributes = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Record build() {
      try {
        Record record = new Record();
        record.data = fieldSetFlags()[0] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        record.attributes = fieldSetFlags()[1] ? this.attributes : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
