# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Export short tag
      run: export VP_LAST_TAG=`git describe --tags`
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Echo VP_LAST_TAG
      run: echo $VP_LAST_TAG
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Davro-message-batch.version=${{ github.ref }}
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

